# Generated by Django 4.1.2 on 2023-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0003_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(),
        ),
    ]
