# Generated by Django 4.1.2 on 2023-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0004_alter_work_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
