# Generated by Django 4.1.2 on 2023-02-08 17:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0005_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
