# Generated by Django 4.1.2 on 2023-02-08 17:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0006_alter_work_content_alter_work_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
