# Generated by Django 4.1.2 on 2023-02-08 19:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0009_delete_achivmnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivmnt',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description', models.CharField(default='', max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
