# Generated by Django 4.1.2 on 2023-02-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0010_achivmnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achivmnt',
        ),
    ]
