# Generated by Django 4.1.2 on 2023-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppp', '0011_delete_achivmnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
